print('Enter the name of cat1:')
catname1=input()
print('Enter the name of cat2:')
catname2=input()
print('Enter the name of cat3:')
catname3=input()
print('Enter the name of cat4:')
catname4=input()
print ('the cat names are:')
print(catname1 + '' + catname2)
